#These are also default settings of a Cellsnake run without any configfile
#basic paramaters
min_cells: 3
min_features: 200 
percent_mt: "10" #Mitochondrial genes maximum percentage, default 10, you can use "auto"
percent_rp: 0 #Ribosomal genes minimum percentage, default no filtering
highly_variable_features: 2000

#doublet filtering, True:T or False:F
doublet_filter: T


#clustering and normalization paramaters
normalization_method: "LogNormalize"
scale_factor: 10000
resolution: "0.8" #default is 0.8, you can write "auto" for automatic detection

#Differential expression paramaters
logfc_threshold: 0.25
test_use: "wilcox"

#plotting paramaters
marker_plots_per_cluster_n: 50

#GO enrichment paramaters
algorithm: "weight01"
statistics: "ks"
mapping: "org.Hs.eg.db"
ontology: "BP"

#alternative route paramaters
##integration params
integration_id: "combined"
integration_resolution: 0.8

#celltypist
celltypist_model: "Immune_All_Low.pkl"

