name: cellsnake
channels:
 - conda-forge
 - bioconda
 - anaconda
 - r
dependencies:
 - r-base==4.2.2
 - snakemake-minimal==7.22.0
 - geos==3.11.1
 - cmake
 - hdf5
 - numba
 - r-xml
 - bedtools
 - samtools
 - kraken2
 - openblas==0.3.21
 - bioconductor-scater
 - pip
 - pip:
   - scipy
   - regex
   - pysam
   - matplotlib<3.7
   - celltypist==1.3.0
   - pandas