name: cellsnake
channels:
 - conda-forge
 - bioconda
 - anaconda
dependencies:
 - r-base
 - snakemake-minimal
 - geos
 - cmake
 - hdf5
 - numba
 - r-xml
 - bedtools
 - samtools
 - kraken2
 - openblas
 - celltypist
 - bioconductor-scater
 - pip
 - pip:
   - scipy
   - regex
   - pysam
