name: cellsnake
channels:
 - conda-forge
 - anaconda
 - bioconda
dependencies:
 - r-base==4.2.2
 #- r-igraph==1.3.1
 - r-igraph
 - r-ggraph==2.1.0
 - r-seurat==4.3.0
 - r-clustree==0.5.0
 - r-ggthemes
 - r-viridis
 - r-librarian
 - r-patchwork
 - r-optparse
 - r-openxlsx
 - r-nmf
 - r-fields
 - r-minqa
 - r-ggpubr
 - r-reticulate
 - r-expm
 - r-ggalluvial
 - r-curl
 - r-tidyseurat
 - r-tidyverse
 #- r-seuratdisk
 - bioconductor-rhdf5lib
 - bioconductor-clusterprofiler==4.6.0
 - bioconductor-scater==1.26.0
 - bioconductor-limma
 - bioconductor-complexheatmap
 - bioconductor-topgo
 - bioconductor-org.hs.eg.db
 - bioconductor-miqc 
 - bioconductor-rhdf5lib
 - bioconductor-singler
 - bioconductor-celldex
 - geos==3.11.1
 - cmake
 - hdf5
 - numba
 - r-xml
 - bedtools
 - samtools
 - kraken2
 - openblas==0.3.21
 - pip
 - pip:
   - scipy>=1.6.2
   - regex>=2021.4.4
   - pysam>=0.16.0.1
   - matplotlib<3.7
   - celltypist==1.3.0
   - pandas
   - levenshtein
   - fuzzywuzzy
   - docopt
   - snakemake>=7.22.0
   - umap-learn
